#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-lastest"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "f35f35995d5d4c88a7e1aec0a50df84f" }
]

[assets]
directory = "./public"
